### ISSUE TITLE
Migrate to Sound Null Safety

### ISSUE THREAD

**Issue by rgr** [komapeb/data_connection_checker#17]
Migrate to sound null safety
Bump up package version

**Comment by rounaktadvi** [comment]
Hey , I have added a Pull Request For Sound Null Safety I hope the maintainer of the package will merge it soon.

**Comment by rgr** [comment]
Thanks @RounakTadvi !

**Comment by rgr** [comment]
so on other packages what we did while waiting for the owner to accept the PR is this :

catcher:
    git:
      url: https://github.com/jhomlala/catcher

@RounakTadvi  Can you make a master branch with your PR ?

**Comment by rounaktadvi** [comment]
@LearningRaph Interesting, I'll see what i can do

**Comment by rounaktadvi** [comment]
Since, @komapeb is not active since December 2019, I republished the package at pub.dev

https://pub.dev/packages/internet_connection_checker/versions/0.0.1

**Comment by rgr** [comment]
Ok thanks. Maybe you should publish a note in the readme stating where the main code comes from, no ? It's only faire to @komapeb. But thanks for publishing !

**Comment by rounaktadvi** [comment]
Sure , Good idea @LearningRaph I'll do that

**Comment by rounaktadvi** [comment]
Done!

**Comment by rounaktadvi** [comment]
I think you can close the issue @LearningRaph
