### ISSUE TITLE
It's still returning true even if my wifi has not active internet connection..

### ISSUE THREAD

**Issue by faizan-jivani** [komapeb/data_connection_checker#3]
It's still returning true even if my wifi has not active internet connection..

> bool result = await DataConnectionChecker().hasConnection;
> if(result == true) {
>   print('YAY! Free cute dog pics!');
> } else {
>   print('No internet :( Reason:');
>   print(DataConnectionChecker().lastTryResults);
> }

**Comment by willladislaw** [comment]
For me, returns false even when there is an active connection!
